### ISSUE TITLE
Series title in URL

### ISSUE THREAD

**Issue by djshadow** [GinoPane/oc-blogtaxonomy-plugin#74] opened 2020-09-02 23:29 UTC
Hey, I want to have something like mywebsite.com/seris-title/post-title/

How do I output the series-title in the URL? That is really an important thing for me now. Only thing I would say keeping me from using octobercms for my site. :)

Thank you.

**Comment by GinoPane** [comment] 2020-09-03 06:57
Hi!

Which component are you using for this and what exactly you are trying to achieve? I mean, what do you use to list such links (probably, posts-in-series component) and to which page (and which component) do they lead?

I believe that the post page uses `rainlab-blog` plugin and that plugin knows nothing about series actually, so links to it cannot contain series by default.

Maybe there could be some solution, but I need to know your intention.

**Comment by djshadow** [comment] 2020-09-03 08:37
I am only using rainlab-blog and blogtaxonomy plugins. I am building a novel website, so the series will be novels(books) in my case, and the blog post will be the chapters. So when I release a chapter(post) it should have the series(novel) name in its URL.
Example https://www.novelmultiverse.com/novel/cheonma-wants-to-live-quietly/chapter-25/
I want to be able to output a URL exactly like this one.
Really need help with it.

**Comment by djshadow** [comment] 2020-09-03 08:41
Awesome, I'm waiting right here for it. Not moving till you've got it done. :)

**Comment by djshadow** [comment] 2020-09-03 13:25
Awesome, awesome, awesome. Checking it now. Thanks a million.

**Comment by GinoPane** [comment] 2020-09-15 14:17
Closing this because it seems that the issue is resolved

**Closed by GinoPane** 2020-09-15 14:17 UTC
Labels: question
